/*  J2TextPrinterTestApplication
    (C) Copyright 2000
    Wildcrest Associates
    http://www.wildcrest.com
This source code may be freely used, modified, incorporated, and
distributed without restriction as part of any software that uses
J2TextPrinter by Wildcrest Associates.
 */
package com.utils;

import java.awt.*;
import javax.swing.*;
import com.wildcrest.j2textprinter.*;

import com.jpe.*;

public class J2TPPageSetupDialog extends javax.swing.JDialog {
	public J2TPPageSetupDialog(Frame parent) {
		super(parent);

		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		// {{INIT_CONTROLS
		setResizable(false);
		setModal(true);
		getContentPane().setLayout(null);
		setSize(619, 384);
		setVisible(false);
		JPanelAll.setLayout(null);
		getContentPane().add(JPanelAll);
		JPanelAll.setBackground(new java.awt.Color(223, 223, 223));
		JPanelAll.setBounds(0, 0, 620, 384);
		JPanelHeaders.setOpaque(false);
		JPanelHeaders.setLayout(new GridLayout(1, 3, 0, 0));
		JPanelAll.add(JPanelHeaders);
		JPanelHeaders.setBounds(6, 6, 610, 34);
		JPanelLeftHeader.setAlignmentY(0.473684F);
		JPanelLeftHeader.setLayout(new BorderLayout(0, 0));
		JPanelHeaders.add(JPanelLeftHeader);
		JPanelLeftHeader.setBackground(new java.awt.Color(223, 223, 223));
		JLabelLeftHeader.setText("Left header");
		JPanelLeftHeader.add(BorderLayout.NORTH, JLabelLeftHeader);
		JLabelLeftHeader.setForeground(java.awt.Color.black);
		JLabelLeftHeader.setFont(new Font("Dialog", Font.BOLD, 11));
		JPanelLeftHeader.add(BorderLayout.SOUTH, JTextFieldLeftHeader);
		JTextFieldLeftHeader.setFont(new Font("Dialog", Font.PLAIN, 11));
		JPanelCenterHeader.setAlignmentY(0.473684F);
		JPanelCenterHeader.setLayout(new BorderLayout(0, 0));
		JPanelHeaders.add(JPanelCenterHeader);
		JPanelCenterHeader.setBackground(new java.awt.Color(223, 223, 223));
		JLabelCenterHeader.setText("Center header");
		JPanelCenterHeader.add(BorderLayout.NORTH, JLabelCenterHeader);
		JLabelCenterHeader.setForeground(java.awt.Color.black);
		JLabelCenterHeader.setFont(new Font("Dialog", Font.BOLD, 11));
		JPanelCenterHeader.add(BorderLayout.SOUTH, JTextFieldCenterHeader);
		JTextFieldCenterHeader.setFont(new Font("Dialog", Font.PLAIN, 11));
		JPanelRightHeader.setAlignmentY(0.473684F);
		JPanelRightHeader.setLayout(new BorderLayout(0, 0));
		JPanelHeaders.add(JPanelRightHeader);
		JPanelRightHeader.setBackground(new java.awt.Color(223, 223, 223));
		JLabelRightHeader.setText("Right header");
		JPanelRightHeader.add(BorderLayout.NORTH, JLabelRightHeader);
		JLabelRightHeader.setForeground(java.awt.Color.black);
		JLabelRightHeader.setFont(new Font("Dialog", Font.BOLD, 11));
		JPanelRightHeader.add(BorderLayout.SOUTH, JTextFieldRightHeader);
		JTextFieldRightHeader.setFont(new Font("Dialog", Font.PLAIN, 11));
		JPanelFooters.setOpaque(false);
		JPanelFooters.setLayout(new GridLayout(1, 3, 0, 0));
		JPanelAll.add(JPanelFooters);
		JPanelFooters.setBounds(6, 42, 610, 34);
		JPanelLeftFooter.setAlignmentY(0.473684F);
		JPanelLeftFooter.setLayout(new BorderLayout(0, 0));
		JPanelFooters.add(JPanelLeftFooter);
		JPanelLeftFooter.setBackground(new java.awt.Color(223, 223, 223));
		JLabelLeftFooter.setText("Left footer");
		JPanelLeftFooter.add(BorderLayout.NORTH, JLabelLeftFooter);
		JLabelLeftFooter.setForeground(java.awt.Color.black);
		JLabelLeftFooter.setFont(new Font("Dialog", Font.BOLD, 11));
		JPanelLeftFooter.add(BorderLayout.SOUTH, JTextFieldLeftFooter);
		JTextFieldLeftFooter.setFont(new Font("Dialog", Font.PLAIN, 11));
		JPanelCenterFooter.setAlignmentY(0.473684F);
		JPanelCenterFooter.setLayout(new BorderLayout(0, 0));
		JPanelFooters.add(JPanelCenterFooter);
		JPanelCenterFooter.setBackground(new java.awt.Color(223, 223, 223));
		JLabelCenterFooter.setText("Center footer");
		JPanelCenterFooter.add(BorderLayout.NORTH, JLabelCenterFooter);
		JLabelCenterFooter.setForeground(java.awt.Color.black);
		JLabelCenterFooter.setFont(new Font("Dialog", Font.BOLD, 11));
		JPanelCenterFooter.add(BorderLayout.SOUTH, JTextFieldCenterFooter);
		JTextFieldCenterFooter.setFont(new Font("Dialog", Font.PLAIN, 11));
		JPanelRightFooter.setAlignmentY(0.473684F);
		JPanelRightFooter.setLayout(new BorderLayout(0, 0));
		JPanelFooters.add(JPanelRightFooter);
		JPanelRightFooter.setBackground(new java.awt.Color(223, 223, 223));
		JLabelRightFooter.setText("Right footer");
		JPanelRightFooter.add(BorderLayout.NORTH, JLabelRightFooter);
		JLabelRightFooter.setForeground(java.awt.Color.black);
		JLabelRightFooter.setFont(new Font("Dialog", Font.BOLD, 11));
		JPanelRightFooter.add(BorderLayout.SOUTH, JTextFieldRightFooter);
		JTextFieldRightFooter.setFont(new Font("Dialog", Font.PLAIN, 11));
		JPanelHeaderFooterDetails.setOpaque(false);
		JPanelHeaderFooterDetails.setLayout(new GridLayout(1, 4, 0, 0));
		JPanelAll.add(JPanelHeaderFooterDetails);
		JPanelHeaderFooterDetails.setBounds(6, 90, 610, 34);
		JPanelGapBelowHeader.setAlignmentY(0.473684F);
		JPanelGapBelowHeader.setLayout(new BorderLayout(0, 0));
		JPanelHeaderFooterDetails.add(JPanelGapBelowHeader);
		JPanelGapBelowHeader.setBackground(new java.awt.Color(223, 223, 223));
		JLabelGapBelowHeader.setText("Gap below header");
		JPanelGapBelowHeader.add(BorderLayout.NORTH, JLabelGapBelowHeader);
		JLabelGapBelowHeader.setForeground(java.awt.Color.black);
		JLabelGapBelowHeader.setFont(new Font("Dialog", Font.BOLD, 11));
		JPanelGapBelowHeader.add(BorderLayout.SOUTH, JTextFieldGapBelowHeader);
		JTextFieldGapBelowHeader.setFont(new Font("Dialog", Font.PLAIN, 11));
		JPanelGapAboveFooter.setAlignmentY(0.473684F);
		JPanelGapAboveFooter.setLayout(new BorderLayout(0, 0));
		JPanelHeaderFooterDetails.add(JPanelGapAboveFooter);
		JPanelGapAboveFooter.setBackground(new java.awt.Color(223, 223, 223));
		JLabelGapAboveFooter.setText("Gap above footer");
		JPanelGapAboveFooter.add(BorderLayout.NORTH, JLabelGapAboveFooter);
		JLabelGapAboveFooter.setForeground(java.awt.Color.black);
		JLabelGapAboveFooter.setFont(new Font("Dialog", Font.BOLD, 11));
		JPanelGapAboveFooter.add(BorderLayout.SOUTH, JTextFieldGapAboveFooter);
		JTextFieldGapAboveFooter.setFont(new Font("Dialog", Font.PLAIN, 11));
		JPanelHeaderAdornments.setLayout(new GridLayout(2, 1, 0, 0));
		JPanelHeaderFooterDetails.add(JPanelHeaderAdornments);
		JCheckBoxAroundHeader.setText("Box around header");
		JCheckBoxAroundHeader.setActionCommand("Box around header");
		JPanelHeaderAdornments.add(JCheckBoxAroundHeader);
		JCheckBoxAroundHeader.setBackground(new java.awt.Color(223, 223, 223));
		JCheckBoxAroundHeader.setForeground(java.awt.Color.black);
		JCheckBoxAroundHeader.setFont(new Font("Dialog", Font.BOLD, 11));
		JCheckBoxLineBelowHeader.setText("Line below header");
		JCheckBoxLineBelowHeader.setActionCommand("Line below header");
		JPanelHeaderAdornments.add(JCheckBoxLineBelowHeader);
		JCheckBoxLineBelowHeader
				.setBackground(new java.awt.Color(223, 223, 223));
		JCheckBoxLineBelowHeader.setForeground(java.awt.Color.black);
		JCheckBoxLineBelowHeader.setFont(new Font("Dialog", Font.BOLD, 11));
		JPanelFooterAdornments.setLayout(new GridLayout(2, 1, 0, 0));
		JPanelHeaderFooterDetails.add(JPanelFooterAdornments);
		JCheckBoxAroundFooter.setText("Box around footer");
		JCheckBoxAroundFooter.setActionCommand("Box around footer");
		JPanelFooterAdornments.add(JCheckBoxAroundFooter);
		JCheckBoxAroundFooter.setBackground(new java.awt.Color(223, 223, 223));
		JCheckBoxAroundFooter.setForeground(java.awt.Color.black);
		JCheckBoxAroundFooter.setFont(new Font("Dialog", Font.BOLD, 11));
		JCheckBoxLineAboveFooter.setText("Line above footer");
		JCheckBoxLineAboveFooter.setActionCommand("Line above footer");
		JPanelFooterAdornments.add(JCheckBoxLineAboveFooter);
		JCheckBoxLineAboveFooter
				.setBackground(new java.awt.Color(223, 223, 223));
		JCheckBoxLineAboveFooter.setForeground(java.awt.Color.black);
		JCheckBoxLineAboveFooter.setFont(new Font("Dialog", Font.BOLD, 11));
		JPanelScaleCenter.setBounds(6, 288, 610, 34);
		JCheckBoxCenteredHorizontally.setText("Centered horinzontally");
		JCheckBoxCenteredHorizontally.setActionCommand("Box around header");
		JPanelScaleCenter.add(JCheckBoxCenteredHorizontally);
		JCheckBoxCenteredHorizontally.setBackground(new java.awt.Color(223,
				223, 223));
		JCheckBoxCenteredHorizontally.setForeground(java.awt.Color.black);
		JCheckBoxCenteredHorizontally
				.setFont(new Font("Dialog", Font.BOLD, 11));
		JCheckBoxCenteredVertically.setText("Centered vertically");
		JCheckBoxCenteredVertically.setActionCommand("Line below header");
		JPanelScaleCenter.add(JCheckBoxCenteredVertically);
		JCheckBoxCenteredVertically.setBackground(new java.awt.Color(223, 223,
				223));
		JCheckBoxCenteredVertically.setForeground(java.awt.Color.black);
		JCheckBoxCenteredVertically.setFont(new Font("Dialog", Font.BOLD, 11));
		JPanelMargins.setOpaque(false);
		JPanelMargins.setLayout(new GridLayout(1, 4, 0, 0));
		JPanelAll.add(JPanelMargins);
		JPanelMargins.setBounds(6, 132, 610, 34);
		JPanelLeftMargin.setAlignmentY(0.473684F);
		JPanelLeftMargin.setLayout(new BorderLayout(0, 0));
		JPanelMargins.add(JPanelLeftMargin);
		JPanelLeftMargin.setBackground(new java.awt.Color(223, 223, 223));
		JLabelLeftMargin.setText("Left margin");
		JPanelLeftMargin.add(BorderLayout.NORTH, JLabelLeftMargin);
		JLabelLeftMargin.setForeground(java.awt.Color.black);
		JLabelLeftMargin.setFont(new Font("Dialog", Font.BOLD, 11));
		JPanelLeftMargin.add(BorderLayout.SOUTH, JTextFieldLeftMargin);
		JTextFieldLeftMargin.setFont(new Font("Dialog", Font.PLAIN, 11));
		JPanelRightMargin.setAlignmentY(0.473684F);
		JPanelRightMargin.setLayout(new BorderLayout(0, 0));
		JPanelMargins.add(JPanelRightMargin);
		JPanelRightMargin.setBackground(new java.awt.Color(223, 223, 223));
		JLabelRightMargin.setText("Right margin");
		JPanelRightMargin.add(BorderLayout.NORTH, JLabelRightMargin);
		JLabelRightMargin.setForeground(java.awt.Color.black);
		JLabelRightMargin.setFont(new Font("Dialog", Font.BOLD, 11));
		JPanelRightMargin.add(BorderLayout.SOUTH, JTextFieldRightMargin);
		JTextFieldRightMargin.setFont(new Font("Dialog", Font.PLAIN, 11));
		JPanelTopMargin.setAlignmentY(0.473684F);
		JPanelTopMargin.setLayout(new BorderLayout(0, 0));
		JPanelMargins.add(JPanelTopMargin);
		JPanelTopMargin.setBackground(new java.awt.Color(223, 223, 223));
		JLabelTopMargin.setText("Top margin");
		JPanelTopMargin.add(BorderLayout.NORTH, JLabelTopMargin);
		JLabelTopMargin.setForeground(java.awt.Color.black);
		JLabelTopMargin.setFont(new Font("Dialog", Font.BOLD, 11));
		JPanelTopMargin.add(BorderLayout.SOUTH, JTextFieldTopMargin);
		JTextFieldTopMargin.setFont(new Font("Dialog", Font.PLAIN, 11));
		JPanelBottomMargin.setAlignmentY(0.473684F);
		JPanelBottomMargin.setLayout(new BorderLayout(0, 0));
		JPanelMargins.add(JPanelBottomMargin);
		JPanelBottomMargin.setBackground(new java.awt.Color(223, 223, 223));
		JLabelBottomMargin.setText("Bottom margin");
		JPanelBottomMargin.add(BorderLayout.NORTH, JLabelBottomMargin);
		JLabelBottomMargin.setForeground(java.awt.Color.black);
		JLabelBottomMargin.setFont(new Font("Dialog", Font.BOLD, 11));
		JPanelBottomMargin.add(BorderLayout.SOUTH, JTextFieldBottomMargin);
		JTextFieldBottomMargin.setFont(new Font("Dialog", Font.PLAIN, 11));
		JPanelUnprintableMargins.setOpaque(false);
		JPanelUnprintableMargins.setLayout(new GridLayout(1, 4, 0, 0));
		JPanelAll.add(JPanelUnprintableMargins);
		JPanelUnprintableMargins.setBounds(6, 174, 610, 34);
		JPanelUnprintableLeftMargin.setAlignmentY(0.473684F);
		JPanelUnprintableLeftMargin.setLayout(new BorderLayout(0, 0));
		JPanelUnprintableMargins.add(JPanelUnprintableLeftMargin);
		JPanelUnprintableLeftMargin.setBackground(new java.awt.Color(223, 223,
				223));
		JLabelUnprintableLeftMargin.setText("Unprintable left margin");
		JPanelUnprintableLeftMargin.add(BorderLayout.NORTH,
				JLabelUnprintableLeftMargin);
		JLabelUnprintableLeftMargin.setForeground(java.awt.Color.black);
		JLabelUnprintableLeftMargin.setFont(new Font("Dialog", Font.BOLD, 11));
		JPanelUnprintableLeftMargin.add(BorderLayout.SOUTH,
				JTextFieldUnprintableLeftMargin);
		JTextFieldUnprintableLeftMargin.setFont(new Font("Dialog", Font.PLAIN,
				11));
		JPanelUnprintableRightMargin.setAlignmentY(0.473684F);
		JPanelUnprintableRightMargin.setLayout(new BorderLayout(0, 0));
		JPanelUnprintableMargins.add(JPanelUnprintableRightMargin);
		JPanelUnprintableRightMargin.setBackground(new java.awt.Color(223, 223,
				223));
		JLabelUnprintableRightMargin.setText("Unprintable right margin");
		JPanelUnprintableRightMargin.add(BorderLayout.NORTH,
				JLabelUnprintableRightMargin);
		JLabelUnprintableRightMargin.setForeground(java.awt.Color.black);
		JLabelUnprintableRightMargin.setFont(new Font("Dialog", Font.BOLD, 11));
		JPanelUnprintableRightMargin.add(BorderLayout.SOUTH,
				JTextFieldUnprintableRightMargin);
		JTextFieldUnprintableRightMargin.setFont(new Font("Dialog", Font.PLAIN,
				11));
		JPanelUnprintableTopMargin.setAlignmentY(0.473684F);
		JPanelUnprintableTopMargin.setLayout(new BorderLayout(0, 0));
		JPanelUnprintableMargins.add(JPanelUnprintableTopMargin);
		JPanelUnprintableTopMargin.setBackground(new java.awt.Color(223, 223,
				223));
		JLabelUnprintableTopMargin.setText("Unprintable top margin");
		JPanelUnprintableTopMargin.add(BorderLayout.NORTH,
				JLabelUnprintableTopMargin);
		JLabelUnprintableTopMargin.setForeground(java.awt.Color.black);
		JLabelUnprintableTopMargin.setFont(new Font("Dialog", Font.BOLD, 11));
		JPanelUnprintableTopMargin.add(BorderLayout.SOUTH,
				JTextFieldUnprintableTopMargin);
		JTextFieldUnprintableTopMargin.setFont(new Font("Dialog", Font.PLAIN,
				11));
		JPanelUnprintableBottomMargin.setAlignmentY(0.473684F);
		JPanelUnprintableBottomMargin.setLayout(new BorderLayout(0, 0));
		JPanelUnprintableMargins.add(JPanelUnprintableBottomMargin);
		JPanelUnprintableBottomMargin.setBackground(new java.awt.Color(223,
				223, 223));
		JLabelUnprintableBottomMargin.setText("Unprintable bottom margin");
		JPanelUnprintableBottomMargin.add(BorderLayout.NORTH,
				JLabelUnprintableBottomMargin);
		JLabelUnprintableBottomMargin.setForeground(java.awt.Color.black);
		JLabelUnprintableBottomMargin
				.setFont(new Font("Dialog", Font.BOLD, 11));
		JPanelUnprintableBottomMargin.add(BorderLayout.SOUTH,
				JTextFieldUnprintableBottomMargin);
		JTextFieldUnprintableBottomMargin.setFont(new Font("Dialog",
				Font.PLAIN, 11));
		JPanelMisc2.setOpaque(false);
		JPanelMisc2.setLayout(new GridLayout(1, 3, 0, 0));
		JPanelAll.add(JPanelMisc2);
		JPanelMisc2.setBounds(6, 216, 610, 34);
		JPanelPrintJobName.setAlignmentY(0.473684F);
		JPanelPrintJobName.setLayout(new BorderLayout(0, 0));
		JPanelMisc2.add(JPanelPrintJobName);
		JPanelPrintJobName.setBackground(new java.awt.Color(223, 223, 223));
		JLabelPrintJobName.setText("Print job name");
		JPanelPrintJobName.add(BorderLayout.NORTH, JLabelPrintJobName);
		JLabelPrintJobName.setBackground(new java.awt.Color(223, 223, 223));
		JLabelPrintJobName.setForeground(java.awt.Color.black);
		JLabelPrintJobName.setFont(new Font("Dialog", Font.BOLD, 11));
		JPanelPrintJobName.add(BorderLayout.SOUTH, JTextFieldPrintJobName);
		JTextFieldPrintJobName.setFont(new Font("Dialog", Font.PLAIN, 11));
		JPanelHeaderFooterFont.setAlignmentY(0.473684F);
		JPanelHeaderFooterFont.setLayout(new BorderLayout(0, 0));
		JPanelMisc2.add(JPanelHeaderFooterFont);
		JPanelHeaderFooterFont.setBackground(new java.awt.Color(223, 223, 223));
		JLabelHeaderFooterFont.setText("Header/footer font");
		JPanelHeaderFooterFont.add(BorderLayout.NORTH, JLabelHeaderFooterFont);
		JLabelHeaderFooterFont.setForeground(java.awt.Color.black);
		JLabelHeaderFooterFont.setFont(new Font("Dialog", Font.BOLD, 11));
		JPanelHeaderFooterFont.add(BorderLayout.SOUTH,
				JTextFieldHeaderFooterFont);
		JTextFieldHeaderFooterFont.setFont(new Font("Dialog", Font.PLAIN, 11));
		JPanelMaximumBodyWidth.setAlignmentY(0.473684F);
		JPanelMaximumBodyWidth.setLayout(new BorderLayout(0, 0));
		JPanelMisc2.add(JPanelMaximumBodyWidth);
		JPanelMaximumBodyWidth.setBackground(new java.awt.Color(223, 223, 223));
		JLabelMaximumBodyWidth.setText("Maximum body width   ");
		JPanelMaximumBodyWidth.add(BorderLayout.NORTH, JLabelMaximumBodyWidth);
		JLabelMaximumBodyWidth.setBackground(new java.awt.Color(223, 223, 223));
		JLabelMaximumBodyWidth.setForeground(java.awt.Color.black);
		JLabelMaximumBodyWidth.setFont(new Font("Dialog", Font.BOLD, 11));
		JTextFieldMaximumBodyWidth.setColumns(4);
		JPanelMaximumBodyWidth.add(BorderLayout.SOUTH,
				JTextFieldMaximumBodyWidth);
		JTextFieldMaximumBodyWidth.setFont(new Font("Dialog", Font.PLAIN, 11));
		JPanelOrientation.setAlignmentY(0.473684F);
		JPanelOrientation.setLayout(new BorderLayout(0, 0));
		JPanelMisc2.add(JPanelOrientation);
		JPanelOrientation.setBackground(new java.awt.Color(223, 223, 223));
		JLabelOrientation.setText("Orientation");
		JPanelOrientation.add(BorderLayout.NORTH, JLabelOrientation);
		JLabelOrientation.setForeground(java.awt.Color.black);
		JLabelOrientation.setFont(new Font("Dialog", Font.BOLD, 11));
		JPanelOrientation.add(BorderLayout.CENTER, JComboBoxOrientation);
		JComboBoxOrientation.setFont(new Font("Dialog", Font.BOLD, 11));
		JPanelMisc1.setOpaque(false);
		JPanelMisc1.setLayout(new GridLayout(1, 4, 0, 0));
		JPanelAll.add(JPanelMisc1);
		JPanelMisc1.setBackground(new java.awt.Color(223, 223, 223));
		JPanelMisc1.setBounds(6, 258, 610, 22);
		JCheckBoxPrintDialogUsed.setText("Use print dialog");
		JCheckBoxPrintDialogUsed.setActionCommand("Box around footer");
		JPanelMisc1.add(JCheckBoxPrintDialogUsed);
		JCheckBoxPrintDialogUsed
				.setBackground(new java.awt.Color(223, 223, 223));
		JCheckBoxPrintDialogUsed.setForeground(java.awt.Color.black);
		JCheckBoxPrintDialogUsed.setFont(new Font("Dialog", Font.BOLD, 11));
		JCheckBoxSeparatePrintThread.setText("Separate print thread");
		JCheckBoxSeparatePrintThread.setActionCommand("Box around footer");
		JPanelMisc1.add(JCheckBoxSeparatePrintThread);
		JCheckBoxSeparatePrintThread.setBackground(new java.awt.Color(223, 223,
				223));
		JCheckBoxSeparatePrintThread.setForeground(java.awt.Color.black);
		JCheckBoxSeparatePrintThread.setFont(new Font("Dialog", Font.BOLD, 11));
		JCheckBoxPrintableAreaCoordinates.setText("Printable area coordinates");
		JCheckBoxPrintableAreaCoordinates.setActionCommand("Box around footer");
		JPanelMisc1.add(JCheckBoxPrintableAreaCoordinates);
		JCheckBoxPrintableAreaCoordinates.setBackground(new java.awt.Color(223,
				223, 223));
		JCheckBoxPrintableAreaCoordinates.setForeground(java.awt.Color.black);
		JCheckBoxPrintableAreaCoordinates.setFont(new Font("Dialog", Font.BOLD,
				11));
		JPanelNumberOfCopies.setAlignmentY(0.473684F);
		JPanelNumberOfCopies.setLayout(new BoxLayout(JPanelNumberOfCopies,
				BoxLayout.X_AXIS));
		JPanelMisc1.add(JPanelNumberOfCopies);
		JPanelNumberOfCopies.setBackground(new java.awt.Color(223, 223, 223));
		JLabelNumberOfCopies.setText("Number of copies  ");
		JPanelNumberOfCopies.add(JLabelNumberOfCopies);
		JLabelNumberOfCopies.setBackground(new java.awt.Color(223, 223, 223));
		JLabelNumberOfCopies.setForeground(java.awt.Color.black);
		JLabelNumberOfCopies.setFont(new Font("Dialog", Font.BOLD, 11));
		JTextFieldNumberOfCopies.setColumns(5);
		JPanelNumberOfCopies.add(JTextFieldNumberOfCopies);
		JTextFieldNumberOfCopies.setFont(new Font("Dialog", Font.PLAIN, 11));
		JPanelOKCancel.setOpaque(false);
		JPanelOKCancel.setLayout(null);
		JPanelAll.add(JPanelOKCancel);
		JPanelOKCancel.setBackground(new java.awt.Color(223, 223, 223));
		JPanelOKCancel.setForeground(java.awt.Color.black);
		JPanelOKCancel.setBounds(108, 342, 372, 24);
		JButtonOK.setText("OK");
		JButtonOK.setActionCommand("OK");
		JPanelOKCancel.add(JButtonOK);
		JButtonOK.setBackground(java.awt.Color.lightGray);
		JButtonOK.setBounds(96, 0, 51, 23);
		JButtonCancel.setText("Cancel");
		JButtonCancel.setActionCommand("Cancel");
		JPanelOKCancel.add(JButtonCancel);
		JButtonCancel.setBackground(java.awt.Color.lightGray);
		JButtonCancel.setBounds(252, 0, 73, 23);
		JPanelScaleCenter.setOpaque(false);
		JPanelScaleCenter.setLayout(new GridLayout(1, 4, 0, 0));
		JPanelAll.add(JPanelScaleCenter);
		JPanelScale.setAlignmentY(0.473684F);
		JPanelScale.setLayout(new BorderLayout(0, 0));
		JPanelScaleCenter.add(JPanelScale);
		JPanelScale.setBackground(new java.awt.Color(223, 223, 223));
		JLabelScale.setText("Scale");
		JPanelScale.add(BorderLayout.NORTH, JLabelScale);
		JLabelScale.setForeground(java.awt.Color.black);
		JLabelScale.setFont(new Font("Dialog", Font.BOLD, 11));
		JPanelScale.add(BorderLayout.SOUTH, JTextFieldScale);
		JTextFieldScale.setFont(new Font("Dialog", Font.PLAIN, 11));
		JPanelPrintPreviewScale.setAlignmentY(0.473684F);
		JPanelPrintPreviewScale.setLayout(new BorderLayout(0, 0));
		JPanelScaleCenter.add(JPanelPrintPreviewScale);
		JPanelPrintPreviewScale
				.setBackground(new java.awt.Color(223, 223, 223));
		JLabelPrintPreviewScale.setText("Print preview scale");
		JPanelPrintPreviewScale
				.add(BorderLayout.NORTH, JLabelPrintPreviewScale);
		JLabelPrintPreviewScale.setForeground(java.awt.Color.black);
		JLabelPrintPreviewScale.setFont(new Font("Dialog", Font.BOLD, 11));
		JPanelPrintPreviewScale.add(BorderLayout.SOUTH,
				JTextFieldPrintPreviewScale);
		JTextFieldPrintPreviewScale.setFont(new Font("Dialog", Font.PLAIN, 11));

		// }}

		JComboBoxOrientation.addItem("PORTRAIT");
		JComboBoxOrientation.addItem("LANDSCAPE");
		JComboBoxOrientation.addItem("REVERSE LANDSCAPE");

		// {{REGISTER_LISTENERS
		SymAction lSymAction = new SymAction();
		JButtonCancel.addActionListener(lSymAction);
		JButtonOK.addActionListener(lSymAction);
		SymItem lSymItem = new SymItem();
		JComboBoxOrientation.addItemListener(lSymItem);
		// }}

		JPanelAll.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
	}

	public J2TPPageSetupDialog(
			com.wildcrest.j2textprinter.J2TextPrinter j2textprinter) {
		this();
		this.j2textprinter = j2textprinter;
		updatePageSetupDialog();
	}

	private void updatePageSetupDialog() {
		if (j2textprinter != null) {
			JTextFieldLeftHeader.setText(j2textprinter.getLeftHeader());
			JTextFieldCenterHeader.setText(j2textprinter.getCenterHeader());
			JTextFieldRightHeader.setText(j2textprinter.getRightHeader());
			JTextFieldLeftFooter.setText(j2textprinter.getLeftFooter());
			JTextFieldCenterFooter.setText(j2textprinter.getCenterFooter());
			JTextFieldRightFooter.setText(j2textprinter.getRightFooter());
			JCheckBoxAroundHeader
					.setSelected(j2textprinter.isBoxAroundHeader());
			JCheckBoxLineBelowHeader.setSelected(j2textprinter
					.isLineBelowHeader());
			JTextFieldGapBelowHeader.setText(Double.toString(j2textprinter
					.getGapBelowHeader()));
			JTextFieldGapAboveFooter.setText(Double.toString(j2textprinter
					.getGapAboveFooter()));
			JCheckBoxAroundFooter
					.setSelected(j2textprinter.isBoxAroundFooter());
			JCheckBoxLineAboveFooter.setSelected(j2textprinter
					.isLineAboveFooter());
			JTextFieldLeftMargin.setText(Double.toString(j2textprinter
					.getLeftMargin()));
			JTextFieldRightMargin.setText(Double.toString(j2textprinter
					.getRightMargin()));
			JTextFieldTopMargin.setText(Double.toString(j2textprinter
					.getTopMargin()));
			JTextFieldBottomMargin.setText(Double.toString(j2textprinter
					.getBottomMargin()));
			JTextFieldUnprintableLeftMargin.setText(Double
					.toString(j2textprinter.getUnprintableLeftMargin()));
			JTextFieldUnprintableRightMargin.setText(Double
					.toString(j2textprinter.getUnprintableRightMargin()));
			JTextFieldUnprintableTopMargin.setText(Double
					.toString(j2textprinter.getUnprintableTopMargin()));
			JTextFieldUnprintableBottomMargin.setText(Double
					.toString(j2textprinter.getUnprintableBottomMargin()));
			JTextFieldPrintJobName.setText(j2textprinter.getPrintJobName());
			JTextFieldHeaderFooterFont.setText(font2String(j2textprinter
					.getHeaderFooterFont()));
			JTextFieldMaximumBodyWidth.setText(Double.toString(j2textprinter
					.getMaximumBodyWidth()));
			if (j2textprinter.getOrientation() == J2TextPrinter.PORTRAIT)
				JComboBoxOrientation.setSelectedIndex(0);
			if (j2textprinter.getOrientation() == J2TextPrinter.LANDSCAPE)
				JComboBoxOrientation.setSelectedIndex(1);
			if (j2textprinter.getOrientation() == J2TextPrinter.REVERSE_LANDSCAPE)
				JComboBoxOrientation.setSelectedIndex(2);
			rememberOrientationAtStart = JComboBoxOrientation
					.getSelectedIndex();
			JCheckBoxPrintDialogUsed.setSelected(j2textprinter
					.isPrintDialogUsed());
			JCheckBoxSeparatePrintThread.setSelected(j2textprinter
					.isSeparatePrintThread());
			JCheckBoxPrintableAreaCoordinates.setSelected(j2textprinter
					.isPrintableAreaCoordinates());
			JTextFieldNumberOfCopies.setText(Integer.toString(j2textprinter
					.getNumberOfCopies()));
			JCheckBoxCenteredHorizontally.setSelected(j2textprinter
					.isCenteredHorizontally());
			JCheckBoxCenteredVertically.setSelected(j2textprinter
					.isCenteredVertically());
			JTextFieldScale.setText(Double.toString(j2textprinter.getScale()));
			JTextFieldPrintPreviewScale.setText(Double.toString(j2textprinter
					.getPrintPreviewScale()));
		}
	}

	private String font2String(Font f) {
		int style = f.getStyle();
		String styleName = "PLAIN";
		if (style == Font.BOLD)
			styleName = "BOLD";
		if (style == Font.ITALIC)
			styleName = "ITALIC";
		return f.getFamily() + "," + styleName + "," + f.getSize();
	}

	public J2TPPageSetupDialog() {
		this((Frame) null);
	}

	public J2TPPageSetupDialog(String sTitle) {
		this();
		setTitle(sTitle);
	}

	public void setVisible(boolean b) {
		updatePageSetupDialog();
		if (b) {
			Rectangle bounds = (getParent()).getBounds();
			Dimension size = getSize();
			setLocation(bounds.x + (bounds.width - size.width) / 2, bounds.y
					+ (bounds.height - size.height) / 2);
		}
		super.setVisible(b);
	}

	static public void main(String args[]) {
		(new J2TPPageSetupDialog()).setVisible(true);
	}

	public void addNotify() {
		// Record the size of the window prior to calling parents addNotify.
		Dimension size = getSize();

		super.addNotify();

		if (frameSizeAdjusted)
			return;
		frameSizeAdjusted = true;

		// Adjust size of frame according to the insets
		Insets insets = getInsets();
		setSize(insets.left + insets.right + size.width, insets.top
				+ insets.bottom + size.height);
	}

	// Used by addNotify
	boolean frameSizeAdjusted = false;

	// {{DECLARE_CONTROLS
	javax.swing.JPanel JPanelAll = new javax.swing.JPanel();
	javax.swing.JPanel JPanelHeaders = new javax.swing.JPanel();
	javax.swing.JPanel JPanelLeftHeader = new javax.swing.JPanel();
	javax.swing.JLabel JLabelLeftHeader = new javax.swing.JLabel();
	javax.swing.JTextField JTextFieldLeftHeader = new javax.swing.JTextField();
	javax.swing.JPanel JPanelCenterHeader = new javax.swing.JPanel();
	javax.swing.JLabel JLabelCenterHeader = new javax.swing.JLabel();
	javax.swing.JTextField JTextFieldCenterHeader = new javax.swing.JTextField();
	javax.swing.JPanel JPanelRightHeader = new javax.swing.JPanel();
	javax.swing.JLabel JLabelRightHeader = new javax.swing.JLabel();
	javax.swing.JTextField JTextFieldRightHeader = new javax.swing.JTextField();
	javax.swing.JPanel JPanelFooters = new javax.swing.JPanel();
	javax.swing.JPanel JPanelLeftFooter = new javax.swing.JPanel();
	javax.swing.JLabel JLabelLeftFooter = new javax.swing.JLabel();
	javax.swing.JTextField JTextFieldLeftFooter = new javax.swing.JTextField();
	javax.swing.JPanel JPanelCenterFooter = new javax.swing.JPanel();
	javax.swing.JLabel JLabelCenterFooter = new javax.swing.JLabel();
	javax.swing.JTextField JTextFieldCenterFooter = new javax.swing.JTextField();
	javax.swing.JPanel JPanelRightFooter = new javax.swing.JPanel();
	javax.swing.JLabel JLabelRightFooter = new javax.swing.JLabel();
	javax.swing.JTextField JTextFieldRightFooter = new javax.swing.JTextField();
	javax.swing.JPanel JPanelHeaderFooterDetails = new javax.swing.JPanel();
	javax.swing.JPanel JPanelGapBelowHeader = new javax.swing.JPanel();
	javax.swing.JLabel JLabelGapBelowHeader = new javax.swing.JLabel();
	javax.swing.JTextField JTextFieldGapBelowHeader = new javax.swing.JTextField();
	javax.swing.JPanel JPanelGapAboveFooter = new javax.swing.JPanel();
	javax.swing.JLabel JLabelGapAboveFooter = new javax.swing.JLabel();
	javax.swing.JTextField JTextFieldGapAboveFooter = new javax.swing.JTextField();
	javax.swing.JPanel JPanelHeaderAdornments = new javax.swing.JPanel();
	javax.swing.JCheckBox JCheckBoxAroundHeader = new javax.swing.JCheckBox();
	javax.swing.JCheckBox JCheckBoxLineBelowHeader = new javax.swing.JCheckBox();
	javax.swing.JPanel JPanelFooterAdornments = new javax.swing.JPanel();
	javax.swing.JCheckBox JCheckBoxAroundFooter = new javax.swing.JCheckBox();
	javax.swing.JCheckBox JCheckBoxLineAboveFooter = new javax.swing.JCheckBox();
	javax.swing.JPanel JPanelMargins = new javax.swing.JPanel();
	javax.swing.JPanel JPanelLeftMargin = new javax.swing.JPanel();
	javax.swing.JLabel JLabelLeftMargin = new javax.swing.JLabel();
	javax.swing.JTextField JTextFieldLeftMargin = new javax.swing.JTextField();
	javax.swing.JPanel JPanelRightMargin = new javax.swing.JPanel();
	javax.swing.JLabel JLabelRightMargin = new javax.swing.JLabel();
	javax.swing.JTextField JTextFieldRightMargin = new javax.swing.JTextField();
	javax.swing.JPanel JPanelTopMargin = new javax.swing.JPanel();
	javax.swing.JLabel JLabelTopMargin = new javax.swing.JLabel();
	javax.swing.JTextField JTextFieldTopMargin = new javax.swing.JTextField();
	javax.swing.JPanel JPanelBottomMargin = new javax.swing.JPanel();
	javax.swing.JLabel JLabelBottomMargin = new javax.swing.JLabel();
	javax.swing.JTextField JTextFieldBottomMargin = new javax.swing.JTextField();
	javax.swing.JPanel JPanelUnprintableMargins = new javax.swing.JPanel();
	javax.swing.JPanel JPanelUnprintableLeftMargin = new javax.swing.JPanel();
	javax.swing.JLabel JLabelUnprintableLeftMargin = new javax.swing.JLabel();
	javax.swing.JTextField JTextFieldUnprintableLeftMargin = new javax.swing.JTextField();
	javax.swing.JPanel JPanelUnprintableRightMargin = new javax.swing.JPanel();
	javax.swing.JLabel JLabelUnprintableRightMargin = new javax.swing.JLabel();
	javax.swing.JTextField JTextFieldUnprintableRightMargin = new javax.swing.JTextField();
	javax.swing.JPanel JPanelUnprintableTopMargin = new javax.swing.JPanel();
	javax.swing.JLabel JLabelUnprintableTopMargin = new javax.swing.JLabel();
	javax.swing.JTextField JTextFieldUnprintableTopMargin = new javax.swing.JTextField();
	javax.swing.JPanel JPanelUnprintableBottomMargin = new javax.swing.JPanel();
	javax.swing.JLabel JLabelUnprintableBottomMargin = new javax.swing.JLabel();
	javax.swing.JTextField JTextFieldUnprintableBottomMargin = new javax.swing.JTextField();
	javax.swing.JPanel JPanelMisc2 = new javax.swing.JPanel();
	javax.swing.JPanel JPanelPrintJobName = new javax.swing.JPanel();
	javax.swing.JLabel JLabelPrintJobName = new javax.swing.JLabel();
	javax.swing.JTextField JTextFieldPrintJobName = new javax.swing.JTextField();
	javax.swing.JPanel JPanelHeaderFooterFont = new javax.swing.JPanel();
	javax.swing.JLabel JLabelHeaderFooterFont = new javax.swing.JLabel();
	javax.swing.JTextField JTextFieldHeaderFooterFont = new javax.swing.JTextField();
	javax.swing.JPanel JPanelMaximumBodyWidth = new javax.swing.JPanel();
	javax.swing.JLabel JLabelMaximumBodyWidth = new javax.swing.JLabel();
	javax.swing.JTextField JTextFieldMaximumBodyWidth = new javax.swing.JTextField();
	javax.swing.JPanel JPanelOrientation = new javax.swing.JPanel();
	javax.swing.JLabel JLabelOrientation = new javax.swing.JLabel();
	javax.swing.JComboBox JComboBoxOrientation = new javax.swing.JComboBox();
	javax.swing.JPanel JPanelMisc1 = new javax.swing.JPanel();
	javax.swing.JCheckBox JCheckBoxPrintDialogUsed = new javax.swing.JCheckBox();
	javax.swing.JCheckBox JCheckBoxSeparatePrintThread = new javax.swing.JCheckBox();
	javax.swing.JCheckBox JCheckBoxPrintableAreaCoordinates = new javax.swing.JCheckBox();
	javax.swing.JPanel JPanelNumberOfCopies = new javax.swing.JPanel();
	javax.swing.JLabel JLabelNumberOfCopies = new javax.swing.JLabel();
	javax.swing.JTextField JTextFieldNumberOfCopies = new javax.swing.JTextField();
	javax.swing.JPanel JPanelOKCancel = new javax.swing.JPanel();
	javax.swing.JButton JButtonOK = new javax.swing.JButton();
	javax.swing.JButton JButtonCancel = new javax.swing.JButton();
	javax.swing.JPanel JPanelScaleCenter = new javax.swing.JPanel();
	javax.swing.JCheckBox JCheckBoxCenteredHorizontally = new javax.swing.JCheckBox();
	javax.swing.JCheckBox JCheckBoxCenteredVertically = new javax.swing.JCheckBox();
	javax.swing.JPanel JPanelScale = new javax.swing.JPanel();
	javax.swing.JLabel JLabelScale = new javax.swing.JLabel();
	javax.swing.JTextField JTextFieldScale = new javax.swing.JTextField();
	javax.swing.JPanel JPanelPrintPreviewScale = new javax.swing.JPanel();
	javax.swing.JLabel JLabelPrintPreviewScale = new javax.swing.JLabel();
	javax.swing.JTextField JTextFieldPrintPreviewScale = new javax.swing.JTextField();
	// }}

	com.wildcrest.j2textprinter.J2TextPrinter j2textprinter;
	int rememberOrientationAtStart;

	class SymAction implements java.awt.event.ActionListener {
		public void actionPerformed(java.awt.event.ActionEvent event) {
			Object object = event.getSource();
			if (object == JButtonCancel)
				JButtonCancel_actionPerformed(event);
			else if (object == JButtonOK)
				JButtonOK_actionPerformed(event);
		}
	}

	void JButtonCancel_actionPerformed(java.awt.event.ActionEvent event) {
		// to do: code goes here.

		JButtonCancel_actionPerformed_Interaction1(event);
	}

	void JButtonCancel_actionPerformed_Interaction1(
			java.awt.event.ActionEvent event) {
		try {
			// JPageSetupDialog Hide the JPageSetupDialog
			JComboBoxOrientation.setSelectedIndex(rememberOrientationAtStart); // restore
																				// orientation
																				// if
																				// cancelled
			if (rememberOrientationAtStart == 0)
				j2textprinter.setOrientation(J2TextPrinter.PORTRAIT);
			if (rememberOrientationAtStart == 1)
				j2textprinter.setOrientation(J2TextPrinter.LANDSCAPE);
			if (rememberOrientationAtStart == 2)
				j2textprinter.setOrientation(J2TextPrinter.REVERSE_LANDSCAPE);
			this.setVisible(false);
		} catch (Exception e) {
		}
	}

	void JButtonOK_actionPerformed(java.awt.event.ActionEvent event) {
		// to do: code goes here.

		JButtonOK_actionPerformed_Interaction1(event);
	}

	void JButtonOK_actionPerformed_Interaction1(java.awt.event.ActionEvent event) {
		updateJ2TextPrinter();
		try {
			// JPageSetupDialog Hide the JPageSetupDialog
			this.setVisible(false);
		} catch (Exception e) {
		}
	}

	private void updateJ2TextPrinter() {
		if (j2textprinter != null) {
			j2textprinter.setLeftHeader(JTextFieldLeftHeader.getText());
			j2textprinter.setCenterHeader(JTextFieldCenterHeader.getText());
			j2textprinter.setRightHeader(JTextFieldRightHeader.getText());
			j2textprinter.setLeftFooter(JTextFieldLeftFooter.getText());
			j2textprinter.setCenterFooter(JTextFieldCenterFooter.getText());
			j2textprinter.setRightFooter(JTextFieldRightFooter.getText());
			j2textprinter
					.setBoxAroundHeader(JCheckBoxAroundHeader.isSelected());
			j2textprinter.setLineBelowHeader(JCheckBoxLineBelowHeader
					.isSelected());
			j2textprinter.setGapBelowHeader(Double.valueOf(
					JTextFieldGapBelowHeader.getText()).doubleValue());
			j2textprinter.setGapAboveFooter(Double.valueOf(
					JTextFieldGapAboveFooter.getText()).doubleValue());
			j2textprinter
					.setBoxAroundFooter(JCheckBoxAroundFooter.isSelected());
			j2textprinter.setLineAboveFooter(JCheckBoxLineAboveFooter
					.isSelected());
			j2textprinter.setLeftMargin(Double.valueOf(
					JTextFieldLeftMargin.getText()).doubleValue());
			j2textprinter.setRightMargin(Double.valueOf(
					JTextFieldRightMargin.getText()).doubleValue());
			j2textprinter.setTopMargin(Double.valueOf(
					JTextFieldTopMargin.getText()).doubleValue());
			j2textprinter.setBottomMargin(Double.valueOf(
					JTextFieldBottomMargin.getText()).doubleValue());
			if (JComboBoxOrientation.getSelectedIndex() == 0)
				j2textprinter.setOrientation(J2TextPrinter.PORTRAIT);
			if (JComboBoxOrientation.getSelectedIndex() == 1)
				j2textprinter.setOrientation(J2TextPrinter.LANDSCAPE);
			if (JComboBoxOrientation.getSelectedIndex() == 2)
				j2textprinter.setOrientation(J2TextPrinter.REVERSE_LANDSCAPE);
			j2textprinter.setUnprintableLeftMargin(Double.valueOf(
					JTextFieldUnprintableLeftMargin.getText()).doubleValue());
			j2textprinter.setUnprintableRightMargin(Double.valueOf(
					JTextFieldUnprintableRightMargin.getText()).doubleValue());
			j2textprinter.setUnprintableTopMargin(Double.valueOf(
					JTextFieldUnprintableTopMargin.getText()).doubleValue());
			j2textprinter.setUnprintableBottomMargin(Double.valueOf(
					JTextFieldUnprintableBottomMargin.getText()).doubleValue());
			j2textprinter.setPrintJobName(JTextFieldPrintJobName.getText());
			j2textprinter
					.setHeaderFooterFont(string2Font(JTextFieldHeaderFooterFont
							.getText()));
			j2textprinter.setMaximumBodyWidth(Double.valueOf(
					JTextFieldMaximumBodyWidth.getText()).doubleValue());
			j2textprinter.setPrintDialogUsed(JCheckBoxPrintDialogUsed
					.isSelected());
			j2textprinter.setSeparatePrintThread(JCheckBoxSeparatePrintThread
					.isSelected());
			j2textprinter
					.setPrintableAreaCoordinates(JCheckBoxPrintableAreaCoordinates
							.isSelected());
			j2textprinter.setNumberOfCopies(Integer.valueOf(
					JTextFieldNumberOfCopies.getText()).intValue());
			j2textprinter.setCenteredHorizontally(JCheckBoxCenteredHorizontally
					.isSelected());
			j2textprinter.setCenteredVertically(JCheckBoxCenteredVertically
					.isSelected());
			j2textprinter.setScale(Double.valueOf(JTextFieldScale.getText())
					.doubleValue());
			j2textprinter.setPrintPreviewScale(Double.valueOf(
					JTextFieldPrintPreviewScale.getText()).doubleValue());
		}
	}

	private Font string2Font(String s) {
		int firstcomma = s.indexOf(",");
		int lastcomma = s.lastIndexOf(",");
		String font = s.substring(0, firstcomma);
		String stylename = s.substring(firstcomma + 1, lastcomma);
		int style = Font.PLAIN;
		if (stylename.equals("BOLD"))
			style = Font.BOLD;
		if (stylename.equals("ITALIC"))
			style = Font.ITALIC;
		int size = Integer.valueOf(s.substring(lastcomma + 1)).intValue();
		return new Font(font, style, size);
	}

	class SymItem implements java.awt.event.ItemListener {
		public void itemStateChanged(java.awt.event.ItemEvent event) {
			Object object = event.getSource();
			if (object == JComboBoxOrientation)
				JComboBoxOrientation_itemStateChanged(event);
		}
	}

	void JComboBoxOrientation_itemStateChanged(java.awt.event.ItemEvent event) {
		// to do: code goes here.
		// change of orientation causes change in unprintable margins
		if (JComboBoxOrientation.getSelectedIndex() == 0)
			j2textprinter.setOrientation(J2TextPrinter.PORTRAIT);
		if (JComboBoxOrientation.getSelectedIndex() == 1)
			j2textprinter.setOrientation(J2TextPrinter.LANDSCAPE);
		if (JComboBoxOrientation.getSelectedIndex() == 2)
			j2textprinter.setOrientation(J2TextPrinter.REVERSE_LANDSCAPE);
		JTextFieldUnprintableLeftMargin.setText(Double.toString(j2textprinter
				.getUnprintableLeftMargin()));
		JTextFieldUnprintableRightMargin.setText(Double.toString(j2textprinter
				.getUnprintableRightMargin()));
		JTextFieldUnprintableTopMargin.setText(Double.toString(j2textprinter
				.getUnprintableTopMargin()));
		JTextFieldUnprintableBottomMargin.setText(Double.toString(j2textprinter
				.getUnprintableBottomMargin()));
		repaint();
	}
}
